AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/MethodLength:
  Max: 25
  CountComments: false
  AllowedMethods: []

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 25

Layout/LineLength:
  Max: 120
